services:
  - type: web
    name: imtisal-maize-api
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
